# Generated by Django 5.2.6 on 2026-09-27 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('users', '0007_staffprofile_stf_license_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prs_id', models.UUIDField(db_column='PRS_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prs_instructions', models.TextField(blank=True, db_column='PRS_INSTRUCTIONS', null=True)),
                ('prs_created_at', models.DateTimeField(auto_now_add=True, db_column='PRS_CREATED_AT')),
                ('prs_updated_at', models.DateTimeField(auto_now=True, db_column='PRS_UPDATED_AT')),
                ('con_id', models.OneToOneField(db_column='CON_ID', on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to='consultations.consultation')),
                ('stf_id', models.ForeignKey(db_column='STF_ID', on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='users.staffprofile')),
            ],
            options={
                'db_table': 'PRESCRIPTION',
                'ordering': ['-prs_created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('pri_id', models.UUIDField(db_column='PRI_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pri_medicine_name', models.CharField(db_column='PRI_MEDICINE_NAME', max_length=255)),
                ('pri_dosage', models.CharField(db_column='PRI_DOSAGE', max_length=100)),
                ('pri_frequency', models.CharField(db_column='PRI_FREQUENCY', max_length=100)),
                ('pri_duration', models.CharField(db_column='PRI_DURATION', max_length=100)),
                ('pri_route', models.CharField(choices=[('ORAL', 'Oral'), ('TOPICAL', 'Topical'), ('INJECTION', 'Injection'), ('EAR', 'Ear'), ('EYE', 'Eye'), ('OTHER', 'Other')], db_column='PRI_ROUTE', max_length=20)),
                ('pri_quantity', models.IntegerField(blank=True, db_column='PRI_QUANTITY', null=True)),
                ('pri_notes', models.TextField(blank=True, db_column='PRI_NOTES', null=True)),
                ('pri_created_at', models.DateTimeField(auto_now_add=True, db_column='PRI_CREATED_AT')),
                ('prs_id', models.ForeignKey(db_column='PRS_ID', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='prescriptions.prescription')),
            ],
            options={
                'db_table': 'PRESCRIPTION_ITEM',
                'ordering': ['pri_created_at'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['stf_id'], name='idx_prs_veterinarian'),
        ),
    ]
