# Generated by Django 5.2.6 on 2026-10-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='pri_generic_name',
            field=models.CharField(blank=True, db_column='PRI_GENERIC_NAME', max_length=255, null=True),
        ),
    ]
