# Generated by Django 6.0.7 on 2026-09-15 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_staffprofile_stf_license_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('ntf_id', models.UUIDField(db_column='NTF_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ntf_title', models.CharField(db_column='NTF_TITLE', max_length=255)),
                ('ntf_message', models.TextField(db_column='NTF_MESSAGE')),
                ('ntf_type', models.CharField(choices=[('APPOINTMENT_CREATED', 'Appointment Created'), ('APPOINTMENT_CONFIRMED', 'Appointment Confirmed'), ('APPOINTMENT_CANCELLED', 'Appointment Cancelled'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('CONSULTATION_AVAILABLE', 'Consultation Available'), ('PRESCRIPTION_AVAILABLE', 'Prescription Available'), ('VACCINATION_REMINDER', 'Vaccination Reminder'), ('AI_SCREENING_COMPLETED', 'Ai Screening Completed'), ('AI_SCREENING_REVIEWED', 'Ai Screening Reviewed'), ('SYSTEM', 'System')], db_column='NTF_TYPE', max_length=30)),
                ('ntf_is_read', models.BooleanField(db_column='NTF_IS_READ', default=False)),
                ('ntf_reference_table', models.CharField(blank=True, db_column='NTF_REFERENCE_TABLE', max_length=100, null=True)),
                ('ntf_reference_id', models.UUIDField(blank=True, db_column='NTF_REFERENCE_ID', null=True)),
                ('ntf_created_at', models.DateTimeField(auto_now_add=True, db_column='NTF_CREATED_AT', db_index=True)),
                ('ntf_read_at', models.DateTimeField(blank=True, db_column='NTF_READ_AT', null=True)),
                ('usr_id', models.ForeignKey(db_column='USR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.user')),
            ],
            options={
                'db_table': 'NOTIFICATION',
                'ordering': ['-ntf_created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['usr_id', 'ntf_is_read'], name='idx_ntf_user_read'), models.Index(fields=['ntf_type'], name='idx_ntf_type')],
            },
        ),
    ]
