# Generated by Django 5.2.6 on 2026-09-27 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointment_apt_screening'),
        ('users', '0007_staffprofile_stf_license_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('con_id', models.UUIDField(db_column='CON_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('con_chief_complaint', models.TextField(blank=True, db_column='CON_CHIEF_COMPLAINT', null=True)),
                ('con_subjective', models.TextField(blank=True, db_column='CON_SUBJECTIVE', null=True)),
                ('con_objective', models.TextField(blank=True, db_column='CON_OBJECTIVE', null=True)),
                ('con_assessment', models.TextField(blank=True, db_column='CON_ASSESSMENT', null=True)),
                ('con_plan', models.TextField(blank=True, db_column='CON_PLAN', null=True)),
                ('con_diagnosis', models.TextField(db_column='CON_DIAGNOSIS')),
                ('con_treatment', models.TextField(blank=True, db_column='CON_TREATMENT', null=True)),
                ('con_notes', models.TextField(blank=True, db_column='CON_NOTES', null=True)),
                ('con_created_at', models.DateTimeField(auto_now_add=True, db_column='CON_CREATED_AT')),
                ('con_updated_at', models.DateTimeField(auto_now=True, db_column='CON_UPDATED_AT')),
                ('apt_id', models.OneToOneField(db_column='APT_ID', on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='appointments.appointment')),
                ('stf_id', models.ForeignKey(db_column='STF_ID', on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='users.staffprofile')),
            ],
            options={
                'db_table': 'CONSULTATION',
                'ordering': ['-con_created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['apt_id'], name='idx_con_appointment'), models.Index(fields=['stf_id'], name='idx_con_veterinarian')],
            },
        ),
    ]
