# Generated by Django 5.2.6 on 2026-07-21 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('brd_id', models.UUIDField(db_column='BRD_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brd_name', models.CharField(db_column='BRD_NAME', max_length=100, unique=True)),
                ('brd_description', models.TextField(blank=True, db_column='BRD_DESCRIPTION', null=True)),
                ('brd_created_at', models.DateTimeField(auto_now_add=True, db_column='BRD_CREATED_AT')),
                ('brd_updated_at', models.DateTimeField(auto_now=True, db_column='BRD_UPDATED_AT')),
            ],
            options={
                'db_table': 'BREED',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.UUIDField(db_column='PET_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pet_name', models.CharField(db_column='PET_NAME', max_length=100)),
                ('pet_sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], db_column='PET_SEX', max_length=10)),
                ('pet_birth_date', models.DateField(blank=True, db_column='PET_BIRTH_DATE', null=True)),
                ('pet_weight', models.DecimalField(blank=True, db_column='PET_WEIGHT', decimal_places=2, max_digits=5, null=True)),
                ('pet_color', models.CharField(blank=True, db_column='PET_COLOR', max_length=100, null=True)),
                ('pet_microchip_no', models.CharField(blank=True, db_column='PET_MICROCHIP_NO', max_length=100, null=True, unique=True)),
                ('pet_profile_image', models.TextField(blank=True, db_column='PET_PROFILE_IMAGE', null=True)),
                ('pet_is_active', models.BooleanField(db_column='PET_IS_ACTIVE', default=True)),
                ('pet_created_at', models.DateTimeField(auto_now_add=True, db_column='PET_CREATED_AT')),
                ('pet_updated_at', models.DateTimeField(auto_now=True, db_column='PET_UPDATED_AT')),
                ('pet_deleted_at', models.DateTimeField(blank=True, db_column='PET_DELETED_AT', db_index=True, null=True)),
                ('brd_id', models.ForeignKey(db_column='BRD_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.breed')),
                ('own_id', models.ForeignKey(db_column='OWN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='owners.ownerprofile')),
            ],
            options={
                'db_table': 'PET',
                'managed': True,
            },
        ),
    ]
