# Generated by Django 5.2.6 on 2026-07-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_qr_code',
            field=models.CharField(blank=True, db_column='PET_QR_CODE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_qr_code_url',
            field=models.TextField(blank=True, db_column='PET_QR_CODE_URL', null=True),
        ),
    ]
