# Generated by Django 6.0.7 on 2026-09-15 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0002_alter_clinic_cln_deleted_at_alter_clinic_cln_status'),
        ('pets', '0002_pet_pet_qr_code_pet_pet_qr_code_url'),
        ('users', '0007_staffprofile_stf_license_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('apt_id', models.UUIDField(db_column='APT_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apt_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('FOLLOW_UP', 'Follow Up'), ('VACCINATION', 'Vaccination'), ('AI_REVIEW', 'Ai Review'), ('EMERGENCY', 'Emergency')], db_column='APT_TYPE', max_length=20)),
                ('apt_status', models.CharField(choices=[('BOOKED', 'Booked'), ('CHECKED_IN', 'Checked In'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_column='APT_STATUS', db_index=True, default='BOOKED', max_length=20)),
                ('apt_scheduled_at', models.DateTimeField(db_column='APT_SCHEDULED_AT')),
                ('apt_reason', models.TextField(blank=True, db_column='APT_REASON', null=True)),
                ('apt_checked_in_at', models.DateTimeField(blank=True, db_column='APT_CHECKED_IN_AT', null=True)),
                ('apt_completed_at', models.DateTimeField(blank=True, db_column='APT_COMPLETED_AT', null=True)),
                ('apt_cancelled_at', models.DateTimeField(blank=True, db_column='APT_CANCELLED_AT', null=True)),
                ('apt_cancellation_reason', models.TextField(blank=True, db_column='APT_CANCELLATION_REASON', null=True)),
                ('apt_created_at', models.DateTimeField(auto_now_add=True, db_column='APT_CREATED_AT')),
                ('apt_updated_at', models.DateTimeField(auto_now=True, db_column='APT_UPDATED_AT')),
                ('apt_deleted_at', models.DateTimeField(blank=True, db_column='APT_DELETED_AT', db_index=True, null=True)),
                ('apt_created_by', models.ForeignKey(db_column='APT_CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to='users.user')),
                ('cln_id', models.ForeignKey(db_column='CLN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinics.clinic')),
                ('pet_id', models.ForeignKey(db_column='PET_ID', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.pet')),
                ('stf_id', models.ForeignKey(blank=True, db_column='STF_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='users.staffprofile')),
            ],
            options={
                'db_table': 'APPOINTMENT',
                'ordering': ['-apt_scheduled_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VetSlot',
            fields=[
                ('vsl_id', models.UUIDField(db_column='VSL_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vsl_date', models.DateField(db_column='VSL_DATE')),
                ('vsl_start_time', models.TimeField(db_column='VSL_START_TIME')),
                ('vsl_end_time', models.TimeField(db_column='VSL_END_TIME')),
                ('vsl_created_at', models.DateTimeField(auto_now_add=True, db_column='VSL_CREATED_AT')),
                ('vsl_updated_at', models.DateTimeField(auto_now=True, db_column='VSL_UPDATED_AT')),
                ('cln_id', models.ForeignKey(db_column='CLN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='vet_slots', to='clinics.clinic')),
                ('stf_id', models.ForeignKey(db_column='STF_ID', on_delete=django.db.models.deletion.CASCADE, related_name='vet_slots', to='users.staffprofile')),
                ('vsl_appointment', models.OneToOneField(blank=True, db_column='VSL_APPOINTMENT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_slot', to='appointments.appointment')),
            ],
            options={
                'db_table': 'VET_SLOT',
                'ordering': ['vsl_date', 'vsl_start_time'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['cln_id', 'apt_scheduled_at'], name='idx_apt_clinic_date'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['stf_id', 'apt_scheduled_at'], name='idx_apt_vet_date'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['pet_id'], name='idx_apt_pet'),
        ),
        migrations.AddConstraint(
            model_name='vetslot',
            constraint=models.UniqueConstraint(fields=('stf_id', 'vsl_date', 'vsl_start_time'), name='uq_vet_slot_vet_date_start'),
        ),
    ]
