# Generated by Django 5.2.6 on 2026-09-25 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_screenings', '0001_initial'),
        ('appointments', '0003_vetslot_vsl_status_alter_appointment_apt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='apt_screening',
            field=models.ForeignKey(blank=True, db_column='APT_SCREENING_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='ai_screenings.aiscreening'),
        ),
    ]
