# Generated by Django 5.2.6 on 2026-07-18 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('cln_id', models.UUIDField(db_column='CLN_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cln_name', models.CharField(db_column='CLN_NAME', max_length=255, unique=True)),
                ('cln_email', models.EmailField(blank=True, db_column='CLN_EMAIL', max_length=255, null=True, unique=True)),
                ('cln_phone', models.CharField(blank=True, db_column='CLN_PHONE', max_length=20, null=True)),
                ('cln_address', models.TextField(blank=True, db_column='CLN_ADDRESS', null=True)),
                ('cln_logo_url', models.TextField(blank=True, db_column='CLN_LOGO_URL', null=True)),
                ('cln_license_no', models.CharField(blank=True, db_column='CLN_LICENSE_NO', max_length=100, null=True)),
                ('cln_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], db_column='CLN_STATUS', default='ACTIVE', max_length=20)),
                ('cln_created_at', models.DateTimeField(auto_now_add=True, db_column='CLN_CREATED_AT')),
                ('cln_updated_at', models.DateTimeField(auto_now=True, db_column='CLN_UPDATED_AT')),
                ('cln_deleted_at', models.DateTimeField(blank=True, db_column='CLN_DELETED_AT', null=True)),
            ],
            options={
                'db_table': 'CLINIC',
                'managed': True,
            },
        ),
    ]
