# Generated by Django 5.2.6 on 2026-07-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='cln_deleted_at',
            field=models.DateTimeField(blank=True, db_column='CLN_DELETED_AT', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='cln_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], db_column='CLN_STATUS', db_index=True, default='ACTIVE', max_length=20),
        ),
    ]
