# Generated by Django 6.0.7 on 2026-09-17 09:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_clinic_cln_deleted_at_alter_clinic_cln_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('cls_id', models.UUIDField(db_column='CLS_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cls_opening_time', models.TimeField(db_column='CLS_OPENING_TIME')),
                ('cls_closing_time', models.TimeField(db_column='CLS_CLOSING_TIME')),
                ('cls_appointment_duration', models.IntegerField(db_column='CLS_APPOINTMENT_DURATION', default=30)),
                ('cls_max_appointments_per_day', models.IntegerField(db_column='CLS_MAX_APPOINTMENTS_PER_DAY', default=50)),
                ('cls_allow_owner_booking', models.BooleanField(db_column='CLS_ALLOW_OWNER_BOOKING', default=True)),
                ('cls_created_at', models.DateTimeField(auto_now_add=True, db_column='CLS_CREATED_AT')),
                ('cls_updated_at', models.DateTimeField(auto_now=True, db_column='CLS_UPDATED_AT')),
                ('cln_id', models.OneToOneField(db_column='CLN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='clinics.clinic')),
            ],
            options={
                'db_table': 'CLINIC_SETTINGS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClinicOperatingHours',
            fields=[
                ('coh_id', models.UUIDField(db_column='COH_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('MON', 'Mon'), ('TUE', 'Tue'), ('WED', 'Wed'), ('THU', 'Thu'), ('FRI', 'Fri'), ('SAT', 'Sat'), ('SUN', 'Sun')], db_column='DAY_OF_WEEK', max_length=3)),
                ('day_index', models.IntegerField(db_column='DAY_INDEX')),
                ('opening_time', models.TimeField(blank=True, db_column='OPENING_TIME', null=True)),
                ('closing_time', models.TimeField(blank=True, db_column='CLOSING_TIME', null=True)),
                ('is_closed', models.BooleanField(db_column='IS_CLOSED', default=False)),
                ('coh_created_at', models.DateTimeField(auto_now_add=True, db_column='COH_CREATED_AT')),
                ('coh_updated_at', models.DateTimeField(auto_now=True, db_column='COH_UPDATED_AT')),
                ('cln_id', models.ForeignKey(db_column='CLN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='clinics.clinic')),
            ],
            options={
                'db_table': 'CLINIC_OPERATING_HOURS',
                'ordering': ['day_index'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('cln_id', 'day_of_week'), name='uq_clinic_operating_hours_clinic_day')],
            },
        ),
    ]
