# Generated by Django 6.0.7 on 2026-09-06 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_clinic_cln_deleted_at_alter_clinic_cln_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('cls_id', models.UUIDField(db_column='CLS_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cls_opening_time', models.TimeField(db_column='CLS_OPENING_TIME', default='09:00')),
                ('cls_closing_time', models.TimeField(db_column='CLS_CLOSING_TIME', default='17:00')),
                ('cls_appointment_duration', models.PositiveIntegerField(db_column='CLS_APPOINTMENT_DURATION', default=30)),
                ('cls_max_appointments_per_day', models.PositiveIntegerField(db_column='CLS_MAX_APPOINTMENTS_PER_DAY', default=50)),
                ('cls_allow_owner_booking', models.BooleanField(db_column='CLS_ALLOW_OWNER_BOOKING', default=True)),
                ('cls_timezone', models.CharField(db_column='CLS_TIMEZONE', default='UTC', max_length=50)),
                ('cls_created_at', models.DateTimeField(auto_now_add=True, db_column='CLS_CREATED_AT')),
                ('cls_updated_at', models.DateTimeField(auto_now=True, db_column='CLS_UPDATED_AT')),
                ('cln_id', models.OneToOneField(db_column='CLN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='clinics.clinic')),
            ],
            options={
                'db_table': 'CLINIC_SETTINGS',
                'managed': True,
            },
        ),
    ]
