# Generated by Django 6.0.7 on 2026-09-09 04:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinicsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicOperatingHours',
            fields=[
                ('coa_id', models.UUIDField(db_column='COA_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], db_column='DAY_OF_WEEK', max_length=3)),
                ('day_index', models.PositiveSmallIntegerField(db_column='DAY_INDEX')),
                ('opening_time', models.TimeField(blank=True, db_column='OPENING_TIME', null=True)),
                ('closing_time', models.TimeField(blank=True, db_column='CLOSING_TIME', null=True)),
                ('is_closed', models.BooleanField(db_column='IS_CLOSED', default=True)),
                ('cln_id', models.ForeignKey(db_column='CLN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='clinics.clinic')),
            ],
            options={
                'db_table': 'CLINIC_OPERATING_HOURS',
                'ordering': ['day_index'],
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('cln_id', 'day_of_week'), name='uq_clinic_operating_hours_day')],
            },
        ),
    ]
