# Generated by Django 6.0.7 on 2026-09-17 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinicsettings_clinicoperatinghours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicoperatinghours',
            name='coh_created_at',
        ),
        migrations.RemoveField(
            model_name='clinicoperatinghours',
            name='coh_updated_at',
        ),
        migrations.AlterField(
            model_name='clinicoperatinghours',
            name='coh_id',
            field=models.UUIDField(db_column='COA_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
