# Generated by Django 5.2.6 on 2026-09-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_seed_operating_hours'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clinicoperatinghours',
            name='uq_clinic_operating_hours_clinic_day',
        ),
        migrations.RenameField(
            model_name='clinicoperatinghours',
            old_name='coh_id',
            new_name='coa_id',
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='cls_timezone',
            field=models.CharField(db_column='CLS_TIMEZONE', default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='clinicoperatinghours',
            name='day_index',
            field=models.PositiveSmallIntegerField(db_column='DAY_INDEX'),
        ),
        migrations.AlterField(
            model_name='clinicoperatinghours',
            name='day_of_week',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], db_column='DAY_OF_WEEK', max_length=3),
        ),
        migrations.AlterField(
            model_name='clinicoperatinghours',
            name='is_closed',
            field=models.BooleanField(db_column='IS_CLOSED', default=True),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='cls_appointment_duration',
            field=models.PositiveIntegerField(db_column='CLS_APPOINTMENT_DURATION', default=30),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='cls_closing_time',
            field=models.TimeField(db_column='CLS_CLOSING_TIME', default='17:00'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='cls_max_appointments_per_day',
            field=models.PositiveIntegerField(db_column='CLS_MAX_APPOINTMENTS_PER_DAY', default=50),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='cls_opening_time',
            field=models.TimeField(db_column='CLS_OPENING_TIME', default='09:00'),
        ),
        migrations.AddConstraint(
            model_name='clinicoperatinghours',
            constraint=models.UniqueConstraint(fields=('cln_id', 'day_of_week'), name='uq_clinic_operating_hours_day'),
        ),
    ]
