# Generated by Django 5.2.6 on 2026-09-25 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_pet_pet_qr_code_pet_pet_qr_code_url'),
        ('users', '0007_staffprofile_stf_license_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('dis_id', models.UUIDField(db_column='DIS_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dis_code', models.CharField(db_column='DIS_CODE', max_length=50, unique=True)),
                ('dis_name', models.CharField(db_column='DIS_NAME', max_length=150, unique=True)),
                ('dis_description', models.TextField(blank=True, db_column='DIS_DESCRIPTION', null=True)),
                ('dis_severity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('UNKNOWN', 'Unknown')], db_column='DIS_SEVERITY', default='UNKNOWN', max_length=10)),
                ('dis_created_at', models.DateTimeField(auto_now_add=True, db_column='DIS_CREATED_AT')),
            ],
            options={
                'db_table': 'DISEASE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AiScreening',
            fields=[
                ('ais_id', models.UUIDField(db_column='AIS_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ais_confidence', models.DecimalField(db_column='AIS_CONFIDENCE', decimal_places=2, max_digits=5)),
                ('ais_model_version', models.CharField(db_column='AIS_MODEL_VERSION', max_length=50)),
                ('ais_inference_time_ms', models.PositiveIntegerField(blank=True, db_column='AIS_INFERENCE_TIME_MS', null=True)),
                ('ais_device', models.CharField(blank=True, db_column='AIS_DEVICE', max_length=100, null=True)),
                ('ais_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('REVIEWED', 'Reviewed'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Dismissed')], db_column='AIS_STATUS', default='PENDING_REVIEW', max_length=20)),
                ('ais_source', models.CharField(choices=[('MOCK', 'Mock Data'), ('DEVICE', 'On-device AI')], db_column='AIS_SOURCE', default='MOCK', max_length=10)),
                ('ais_created_at', models.DateTimeField(auto_now_add=True, db_column='AIS_CREATED_AT', db_index=True)),
                ('pet_id', models.ForeignKey(db_column='PET_ID', on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='pets.pet')),
                ('usr_id', models.ForeignKey(db_column='USR_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings', to='users.user')),
                ('dis_id', models.ForeignKey(db_column='DIS_ID', on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='ai_screenings.disease')),
            ],
            options={
                'db_table': 'AI_SCREENING',
                'ordering': ['-ais_created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['pet_id', 'ais_created_at'], name='idx_ais_pet_created'), models.Index(fields=['ais_status'], name='idx_ais_status')],
            },
        ),
    ]
