# Generated by Django 5.2.6 on 2026-10-06 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_screenings', '0002_seed_diseases'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiscreening',
            name='ais_compared_at',
            field=models.DateTimeField(blank=True, db_column='AIS_COMPARED_AT', null=True),
        ),
        migrations.AddField(
            model_name='aiscreening',
            name='ais_compared_diagnosis',
            field=models.TextField(blank=True, db_column='AIS_COMPARED_DIAGNOSIS', null=True),
        ),
        migrations.AddField(
            model_name='aiscreening',
            name='ais_is_correct',
            field=models.BooleanField(blank=True, db_column='AIS_IS_CORRECT', null=True),
        ),
        migrations.AddField(
            model_name='aiscreening',
            name='con_id',
            field=models.ForeignKey(blank=True, db_column='CON_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenings', to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='aiscreening',
            name='ais_source',
            field=models.CharField(choices=[('DEVICE', 'On-device AI')], db_column='AIS_SOURCE', default='DEVICE', max_length=10),
        ),
    ]
