# Generated by Django 5.2.6 on 2026-09-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_screenings', '0002_seed_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiscreening',
            name='ais_check_at',
            field=models.DateTimeField(blank=True, db_column='AIS_CHECK_AT', null=True),
        ),
        migrations.AddField(
            model_name='aiscreening',
            name='ais_check_model',
            field=models.CharField(blank=True, db_column='AIS_CHECK_MODEL', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='aiscreening',
            name='ais_check_notes',
            field=models.TextField(blank=True, db_column='AIS_CHECK_NOTES', default=''),
        ),
        migrations.AddField(
            model_name='aiscreening',
            name='ais_check_verdict',
            field=models.CharField(blank=True, choices=[('AGREE', 'Agree'), ('DISAGREE', 'Disagree'), ('UNCERTAIN', 'Uncertain'), ('UNAVAILABLE', 'Unavailable')], db_column='AIS_CHECK_VERDICT', max_length=20, null=True),
        ),
    ]
