# Generated by Django 5.2.6 on 2026-09-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_screenings', '0003_aiscreening_ais_check_at_aiscreening_ais_check_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiscreening',
            name='ais_check_remedy',
            field=models.TextField(blank=True, db_column='AIS_CHECK_REMEDY', default=''),
        ),
    ]
