# Generated by Django 5.2.6 on 2026-09-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_screenings', '0004_aiscreening_ais_check_remedy'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiscreening',
            name='ais_refinement',
            field=models.JSONField(blank=True, db_column='AIS_REFINEMENT', null=True),
        ),
    ]
