# Generated by Django 5.2.6 on 2026-07-19 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('adl_id', models.UUIDField(db_column='ADL_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usr_id', models.UUIDField(db_column='USR_ID')),
                ('adl_action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('AI_SCREENING', 'Ai Screening'), ('BOOK_APPOINTMENT', 'Book Appointment'), ('UPLOAD_ATTACHMENT', 'Upload Attachment'), ('EXPORT_REPORT', 'Export Report')], db_column='ADL_ACTION', max_length=50)),
                ('adl_module', models.CharField(db_column='ADL_MODULE', max_length=100)),
                ('adl_table_name', models.CharField(db_column='ADL_TABLE_NAME', max_length=100)),
                ('adl_record_id', models.UUIDField(db_column='ADL_RECORD_ID')),
                ('adl_description', models.TextField(blank=True, db_column='ADL_DESCRIPTION', null=True)),
                ('adl_old_values', models.JSONField(blank=True, db_column='ADL_OLD_VALUES', null=True)),
                ('adl_new_values', models.JSONField(blank=True, db_column='ADL_NEW_VALUES', null=True)),
                ('adl_ip_address', models.CharField(blank=True, db_column='ADL_IP_ADDRESS', max_length=50, null=True)),
                ('adl_device', models.CharField(blank=True, db_column='ADL_DEVICE', max_length=255, null=True)),
                ('adl_created_at', models.DateTimeField(auto_now_add=True, db_column='ADL_CREATED_AT')),
            ],
            options={
                'db_table': 'AUDIT_LOG',
                'managed': True,
            },
        ),
    ]
