# Generated by Django 5.2.6 on 2026-07-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='adl_created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='ADL_CREATED_AT', db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='adl_record_id',
            field=models.UUIDField(db_column='ADL_RECORD_ID', db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='adl_table_name',
            field=models.CharField(db_column='ADL_TABLE_NAME', db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='usr_id',
            field=models.UUIDField(db_column='USR_ID', db_index=True),
        ),
    ]
