# Generated by Django 6.0.7 on 2026-09-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0002_alter_auditlog_adl_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='adl_action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTER', 'Register'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('AI_SCREENING', 'Ai Screening'), ('BOOK_APPOINTMENT', 'Book Appointment'), ('UPLOAD_ATTACHMENT', 'Upload Attachment'), ('EXPORT_REPORT', 'Export Report'), ('UPDATE_CLINIC_PROFILE', 'Update Clinic Profile'), ('UPDATE_CLINIC_SETTINGS', 'Update Clinic Settings'), ('UPLOAD_LOGO', 'Upload Logo')], db_column='ADL_ACTION', max_length=50),
        ),
    ]
