/**
 * Computes the OOD reference vector for AI skin screening using TF.js.
 *
 * The app measures a photo against this reference to decide whether the image
 * looks like dog skin at all. It MUST be produced by the same engine that
 * scores at runtime: a reference generated by Python Keras does not line up
 * with TF.js features, which shifts every similarity reading and makes an
 * accurate threshold impossible to pick.
 *
 * This script therefore runs the exact same pipeline as the app:
 *
 *   decode (JPEG via the app's own decoder) -> resizeBilinear -> expandDims
 *     -> global_average_pooling2d features
 *
 * Pure-JS CPU inference is slow (~6s/image), so work is sharded across worker
 * threads. Results are order-independent: every image contributes one feature
 * vector and the aggregate is a plain mean.
 *
 * Usage:
 *   node scripts/compute_training_reference_tfjs.js <trainDir> <outFile> [evalDir] [workers]
 *
 * Example:
 *   node scripts/compute_training_reference_tfjs.js \
 *     "C:\path\to\ProcessedDataset224_Clean_5class\Train" \
 *     "assets/model/training_reference.json" \
 *     "C:\path\to\ProcessedDataset224_Clean_5class\Test" 8
 */

const fs = require('fs')
const path = require('path')
const os = require('os')
const { Worker, isMainThread, workerData, parentPort } = require('worker_threads')

const tf = require('@tensorflow/tfjs')
const { decodeJpeg } = require('@tensorflow/tfjs-react-native/dist/decode_image')
const { PNG } = require('pngjs')
const { Normalization, Rescaling } = require('../ai/services/customLayers')

const MODEL_DIR = path.resolve(__dirname, '..', 'assets', 'model')
const MODEL_JSON_PATH = path.join(MODEL_DIR, 'model.json')
const WEIGHTS_PATH = path.join(MODEL_DIR, 'weights.bin')
const INPUT_SIZE = 224
const EXPECTED_WEIGHTS_BYTES = 17670816

const IMAGE_RE = /\.(jpg|jpeg|png)$/i

function listImages(dir) {
  const out = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) out.push(...listImages(full))
    else if (IMAGE_RE.test(entry.name)) out.push(full)
  }
  return out.sort()
}

function formatOf(file) {
  return path.extname(file).slice(1).toLowerCase() === 'png' ? 'png' : 'jpeg'
}

function loadModel() {
  const modelJSON = JSON.parse(fs.readFileSync(MODEL_JSON_PATH, 'utf8'))

  // A Node Buffer is a view onto a shared ArrayBuffer pool, so buffer.buffer
  // can expose unrelated bytes beyond this file. Slice to the exact range.
  const wBuf = fs.readFileSync(WEIGHTS_PATH)
  const weightData = wBuf.buffer.slice(wBuf.byteOffset, wBuf.byteOffset + wBuf.byteLength)

  if (weightData.byteLength !== EXPECTED_WEIGHTS_BYTES) {
    throw new Error(
      `weights.bin is ${weightData.byteLength} bytes, expected ${EXPECTED_WEIGHTS_BYTES}. Refusing to load.`,
    )
  }

  tf.serialization.registerClass(Normalization)
  tf.serialization.registerClass(Rescaling)

  return tf.loadLayersModel(
    tf.io.fromMemory({
      modelTopology: modelJSON.modelTopology,
      weightSpecs: modelJSON.weightsManifest[0].weights,
      weightData,
    }),
  )
}

/**
 * Decodes to an int32 [h, w, 3] tensor.
 *
 * JPEG goes through the app's own decoder so the reference sees byte-identical
 * pixels to what the device produces. PNG has no app-side decoder, so it is
 * read with pngjs and alpha is dropped to keep the channel layout identical.
 */
function decodeImageFile(file) {
  const buffer = fs.readFileSync(file)

  if (formatOf(file) === 'png') {
    // pngjs needs a Node Buffer (it calls readUInt32BE), not a Uint8Array.
    const png = PNG.sync.read(buffer)
    if (png.data.length !== png.width * png.height * 4) {
      throw new Error(`${file}: unexpected PNG buffer length ${png.data.length}`)
    }
    const rgb = new Int32Array(png.width * png.height * 3)
    let transparent = 0
    for (let px = 0; px < png.width * png.height; px++) {
      const s = px * 4
      const d = px * 3
      rgb[d] = png.data[s]
      rgb[d + 1] = png.data[s + 1]
      rgb[d + 2] = png.data[s + 2]
      if (png.data[s + 3] !== 255) transparent++
    }
    if (transparent > 0) {
      console.warn(`  WARNING: ${path.basename(file)} has ${transparent} non-opaque pixels (alpha dropped)`)
    }
    return tf.tensor3d(rgb, [png.height, png.width, 3], 'int32')
  }

  return decodeJpeg(new Uint8Array(buffer), 3)
}

async function extractFeatures(featureModel, file) {
  const decoded = decodeImageFile(file)
  const resized = tf.image.resizeBilinear(decoded, [INPUT_SIZE, INPUT_SIZE])
  const batched = tf.expandDims(resized, 0)
  decoded.dispose()
  resized.dispose()

  const features = featureModel.predict(batched)
  const data = await features.data()
  features.dispose()
  batched.dispose()
  return Float32Array.from(data)
}

// ---------------------------------------------------------------- worker ---

async function runWorker() {
  await tf.setBackend('cpu')
  await tf.ready()

  const model = await loadModel()
  const gapLayer = model.getLayer('global_average_pooling2d')
  const featureModel = tf.model({ inputs: model.inputs, outputs: gapLayer.output })

  const out = []
  const total = workerData.files.length
  for (const file of workerData.files) {
    out.push(await extractFeatures(featureModel, file))
    if (out.length % 25 === 0 || out.length === total) {
      parentPort.postMessage({ type: 'progress', n: out.length })
    }
  }

  parentPort.postMessage({ type: 'done', features: out })
}

if (!isMainThread) {
  runWorker().catch((err) => {
    parentPort.postMessage({ type: 'error', message: err.message, stack: err.stack })
  })
}

// ------------------------------------------------------------------ main ---

function cosineSimilarity(a, b) {
  let dot = 0
  let na = 0
  let nb = 0
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i]
    na += a[i] * a[i]
    nb += b[i] * b[i]
  }
  return dot / (Math.sqrt(na) * Math.sqrt(nb))
}

function stats(values) {
  if (values.length === 0) return null
  const sorted = [...values].sort((a, b) => a - b)
  const at = (q) => sorted[Math.min(sorted.length - 1, Math.floor(sorted.length * q))]
  return {
    n: values.length,
    min: sorted[0],
    p05: at(0.05),
    mean: values.reduce((s, v) => s + v, 0) / values.length,
    p95: at(0.95),
    max: sorted[sorted.length - 1],
  }
}

function printStats(label, values) {
  const s = stats(values)
  if (!s) {
    console.log(`  ${label.padEnd(16)} (none)`)
    return
  }
  console.log(
    `  ${label.padEnd(16)} n=${String(s.n).padStart(4)}  min=${s.min.toFixed(3)}  p05=${s.p05.toFixed(3)}` +
      `  mean=${s.mean.toFixed(3)}  p95=${s.p95.toFixed(3)}  max=${s.max.toFixed(3)}`,
  )
}

let SHARD_TOTAL = 0
let SHARD_DONE = 0

function runShard(files) {
  return new Promise((resolve, reject) => {
    const worker = new Worker(__filename, { workerData: { files } })
    const features = []
    worker.on('message', (msg) => {
      if (msg.type === 'progress') {
        process.stdout.write(`\r  processed ${SHARD_DONE + msg.n}/${SHARD_TOTAL}`)
      } else if (msg.type === 'done') {
        features.push(...msg.features)
        resolve(features)
      } else if (msg.type === 'error') {
        reject(new Error(`${msg.message}\n${msg.stack}`))
      }
    })
    worker.on('error', reject)
    worker.on('exit', (code) => {
      if (code !== 0) reject(new Error(`worker exited with code ${code}`))
    })
  })
}

async function extractAll(files, workers) {
  SHARD_TOTAL = files.length
  SHARD_DONE = 0

  const shards = []
  const size = Math.ceil(files.length / workers)
  for (let i = 0; i < files.length; i += size) shards.push(files.slice(i, i + size))

  console.log(`  ${files.length} images across ${shards.length} workers`)

  const settled = await Promise.all(
    shards.map(async (shard) => {
      const res = await runShard(shard)
      SHARD_DONE += shard.length
      return res
    }),
  )
  process.stdout.write('\n')

  const flat = settled.flat()
  return files.map((file, i) => ({ file, format: formatOf(file), feature: flat[i] }))
}

function classOf(file) {
  return path.basename(path.dirname(file))
}

async function main() {
  const trainDir = process.argv[2]
  const outFile = process.argv[3]
  const evalDir = process.argv[4]
  const workers = Number(process.argv[5]) || Math.max(1, Math.min(8, os.cpus().length - 2))

  if (!trainDir || !outFile) {
    console.error('Usage: node scripts/compute_training_reference_tfjs.js <trainDir> <outFile> [evalDir] [workers]')
    process.exit(1)
  }

  console.log('='.repeat(70))
  console.log('COMPUTE TRAINING REFERENCE (TF.js)')
  console.log('='.repeat(70))
  console.log(`tfjs ${tf.version.tfjs}  workers=${workers}`)

  const trainFiles = listImages(trainDir)
  if (trainFiles.length === 0) throw new Error(`No images found in ${trainDir}`)
  const fmtCounts = trainFiles.reduce((acc, f) => {
    acc[formatOf(f)] = (acc[formatOf(f)] || 0) + 1
    return acc
  }, {})
  console.log(`Training images: ${trainFiles.length}`)
  console.log(`  ${Object.entries(fmtCounts).map(([k, v]) => `${v} ${k}`).join(', ')}`)

  const started = Date.now()
  const train = await extractAll(trainFiles, workers)
  console.log(`  extracted in ${((Date.now() - started) / 1000).toFixed(1)}s`)

  const features = train.map((t) => t.feature)
  const classes = [...new Set(trainFiles.map(classOf))].sort()
  const dim = features[0].length

  const mean = new Float64Array(dim)
  const std = new Float64Array(dim)
  for (const vec of features) for (let d = 0; d < dim; d++) mean[d] += vec[d]
  for (let d = 0; d < dim; d++) mean[d] /= features.length
  for (const vec of features) {
    for (let d = 0; d < dim; d++) {
      const diff = vec[d] - mean[d]
      std[d] += diff * diff
    }
  }
  for (let d = 0; d < dim; d++) std[d] = Math.sqrt(std[d] / features.length)

  const reference = {
    mean_feature: Array.from(mean),
    std_feature: Array.from(std),
    feature_dim: dim,
    num_images: features.length,
    classes,
    backend: `tfjs-${tf.version.tfjs}-cpu`,
    description:
      'Mean and std of global_average_pooling2d features from the training set, computed with TF.js to match on-device inference.',
  }

  const outPath = path.resolve(outFile)
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, JSON.stringify(reference, null, 2))
  console.log(`\nWrote ${outFile} (${fs.statSync(outPath).size} bytes)`)

  console.log('\n' + '='.repeat(70))
  console.log('VALIDATION - cosine similarity against the new mean')
  console.log('='.repeat(70))

  const meanVec = Float32Array.from(mean)
  const simOf = (t) => cosineSimilarity(t.feature, meanVec)

  printStats('training all', features.map((_, i) => simOf(train[i])))
  for (const fmt of Object.keys(fmtCounts)) {
    printStats(`  ${fmt}`, train.filter((t) => t.format === fmt).map(simOf))
  }
  for (const cls of classes) {
    printStats(`  ${cls}`, train.filter((t) => classOf(t.file) === cls).map(simOf))
  }

  if (evalDir && fs.existsSync(evalDir)) {
    const evalFiles = listImages(evalDir)
    console.log(`\n  held-out eval: ${evalFiles.length} images`)
    const evalData = await extractAll(evalFiles, workers)
    printStats('eval all', evalData.map(simOf))
    for (const cls of classes) {
      printStats(`  ${cls}`, evalData.filter((t) => classOf(t.file) === cls).map(simOf))
    }
  }

  console.log('\nInterpretation:')
  console.log('  These are same-engine numbers. The device (WebGL) may still differ,')
  console.log('  so calibrate the final threshold from real device logs.')
}

if (isMainThread) {
  main().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
