# Generated by Django 5.2.6 on 2026-07-21 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_revokedtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('own_id', models.UUIDField(db_column='OWN_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('own_first_name', models.CharField(db_column='OWN_FIRST_NAME', max_length=100)),
                ('own_last_name', models.CharField(db_column='OWN_LAST_NAME', max_length=100)),
                ('own_phone', models.CharField(blank=True, db_column='OWN_PHONE', max_length=20, null=True)),
                ('own_address', models.TextField(blank=True, db_column='OWN_ADDRESS', null=True)),
                ('own_profile_image', models.TextField(blank=True, db_column='OWN_PROFILE_IMAGE', null=True)),
                ('own_created_at', models.DateTimeField(auto_now_add=True, db_column='OWN_CREATED_AT')),
                ('own_updated_at', models.DateTimeField(auto_now=True, db_column='OWN_UPDATED_AT')),
                ('usr_id', models.OneToOneField(db_column='USR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to='users.user')),
            ],
            options={
                'db_table': 'OWNER_PROFILE',
                'managed': True,
            },
        ),
    ]
