# Generated by Django 5.2.6 on 2026-07-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='own_first_name',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='own_last_name',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='own_phone',
        ),
    ]
