# Generated by Django 5.2.6 on 2026-09-27 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('pets', '0002_pet_pet_qr_code_pet_pet_qr_code_url'),
        ('users', '0007_staffprofile_stf_license_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('vac_id', models.UUIDField(db_column='VAC_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vac_name', models.CharField(db_column='VAC_NAME', max_length=255)),
                ('vac_brand', models.CharField(blank=True, db_column='VAC_BRAND', max_length=255, null=True)),
                ('vac_batch_no', models.CharField(blank=True, db_column='VAC_BATCH_NO', max_length=100, null=True)),
                ('vac_dose', models.CharField(db_column='VAC_DOSE', max_length=100)),
                ('vac_route', models.CharField(choices=[('SUBCUTANEOUS', 'Subcutaneous'), ('INTRAMUSCULAR', 'Intramuscular'), ('INTRAVENOUS', 'Intravenous'), ('ORAL', 'Oral'), ('OTHER', 'Other')], db_column='VAC_ROUTE', max_length=20)),
                ('vac_date_given', models.DateField(db_column='VAC_DATE_GIVEN')),
                ('vac_next_due', models.DateField(blank=True, db_column='VAC_NEXT_DUE', null=True)),
                ('vac_notes', models.TextField(blank=True, db_column='VAC_NOTES', null=True)),
                ('vac_created_at', models.DateTimeField(auto_now_add=True, db_column='VAC_CREATED_AT')),
                ('vac_updated_at', models.DateTimeField(auto_now=True, db_column='VAC_UPDATED_AT')),
                ('con_id', models.ForeignKey(db_column='CON_ID', on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='consultations.consultation')),
                ('pet_id', models.ForeignKey(db_column='PET_ID', on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='pets.pet')),
                ('stf_id', models.ForeignKey(db_column='STF_ID', on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='users.staffprofile')),
            ],
            options={
                'db_table': 'VACCINATION_RECORD',
                'ordering': ['-vac_date_given', '-vac_created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['pet_id'], name='idx_vac_pet'), models.Index(fields=['con_id'], name='idx_vac_consultation'), models.Index(fields=['stf_id'], name='idx_vac_veterinarian'), models.Index(fields=['vac_next_due'], name='idx_vac_next_due')],
            },
        ),
    ]
