# Generated by Django 5.2.6 on 2026-09-29 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('users', '0007_staffprofile_stf_license_expiration_date'),
        ('vaccinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='vac_source',
            field=models.CharField(choices=[('VET', 'Vet'), ('OWNER', 'Owner')], db_column='VAC_SOURCE', default='VET', max_length=10),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='con_id',
            field=models.ForeignKey(blank=True, db_column='CON_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='stf_id',
            field=models.ForeignKey(blank=True, db_column='STF_ID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='users.staffprofile'),
        ),
    ]
