# Generated by Django 5.2.6 on 2026-07-18 08:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('usr_id', models.UUIDField(db_column='USR_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usr_email', models.EmailField(db_column='USR_EMAIL', max_length=255, unique=True)),
                ('usr_password_hash', models.CharField(db_column='USR_PASSWORD_HASH', max_length=255)),
                ('usr_role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CLINIC_ADMIN', 'Clinic Admin'), ('VETERINARIAN', 'Veterinarian'), ('RECEPTIONIST', 'Receptionist'), ('OWNER', 'Owner')], db_column='USR_ROLE', max_length=20)),
                ('usr_first_name', models.CharField(db_column='USR_FIRST_NAME', max_length=100)),
                ('usr_last_name', models.CharField(db_column='USR_LAST_NAME', max_length=100)),
                ('usr_phone', models.CharField(blank=True, db_column='USR_PHONE', max_length=20, null=True)),
                ('usr_is_active', models.BooleanField(db_column='USR_IS_ACTIVE', default=True)),
                ('usr_email_verified', models.BooleanField(db_column='USR_EMAIL_VERIFIED', default=False)),
                ('usr_must_change_password', models.BooleanField(db_column='USR_MUST_CHANGE_PASSWORD', default=False)),
                ('usr_last_login', models.DateTimeField(blank=True, db_column='USR_LAST_LOGIN', null=True)),
                ('usr_created_at', models.DateTimeField(auto_now_add=True, db_column='USR_CREATED_AT')),
                ('usr_updated_at', models.DateTimeField(auto_now=True, db_column='USR_UPDATED_AT')),
                ('usr_deleted_at', models.DateTimeField(blank=True, db_column='USR_DELETED_AT', null=True)),
            ],
            options={
                'db_table': 'USER',
                'managed': True,
            },
        ),
    ]
