# Generated by Django 5.2.6 on 2026-07-19 20:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('stf_id', models.UUIDField(db_column='STF_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stf_first_name', models.CharField(db_column='STF_FIRST_NAME', max_length=100)),
                ('stf_last_name', models.CharField(db_column='STF_LAST_NAME', max_length=100)),
                ('stf_phone', models.CharField(blank=True, db_column='STF_PHONE', max_length=20, null=True)),
                ('stf_license_number', models.CharField(blank=True, db_column='STF_LICENSE_NUMBER', max_length=100, null=True)),
                ('stf_position', models.CharField(choices=[('CLINIC_ADMIN', 'Clinic Admin'), ('VETERINARIAN', 'Veterinarian'), ('RECEPTIONIST', 'Receptionist')], db_column='STF_POSITION', max_length=20)),
                ('stf_created_at', models.DateTimeField(auto_now_add=True, db_column='STF_CREATED_AT')),
                ('stf_updated_at', models.DateTimeField(auto_now=True, db_column='STF_UPDATED_AT')),
                ('cln_id', models.ForeignKey(db_column='CLN_ID', on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic')),
                ('usr_id', models.OneToOneField(db_column='USR_ID', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'STAFF_PROFILE',
                'managed': True,
            },
        ),
    ]
