# Generated by Django 5.2.6 on 2026-07-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usr_deleted_at',
            field=models.DateTimeField(blank=True, db_column='USR_DELETED_AT', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usr_is_active',
            field=models.BooleanField(db_column='USR_IS_ACTIVE', db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usr_role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('CLINIC_ADMIN', 'Clinic Admin'), ('VETERINARIAN', 'Veterinarian'), ('RECEPTIONIST', 'Receptionist'), ('OWNER', 'Owner')], db_column='USR_ROLE', db_index=True, max_length=20),
        ),
    ]
