# Generated by Django 5.2.6 on 2026-07-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_usr_deleted_at_alter_user_usr_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usr_token_version',
            field=models.IntegerField(db_column='USR_TOKEN_VERSION', default=0),
        ),
    ]
