# Generated by Django 5.2.6 on 2026-07-21 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_usr_token_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedToken',
            fields=[
                ('rvt_id', models.UUIDField(db_column='RVT_ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usr_id', models.UUIDField(db_column='USR_ID', db_index=True)),
                ('rvt_jti', models.CharField(db_column='RVT_JTI', max_length=255, unique=True)),
                ('rvt_created_at', models.DateTimeField(auto_now_add=True, db_column='RVT_CREATED_AT')),
            ],
            options={
                'db_table': 'REVOKED_TOKEN',
                'managed': True,
            },
        ),
    ]
