# Generated by Django 5.2.6 on 2026-07-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_revokedtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='stf_first_name',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='stf_last_name',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='stf_phone',
        ),
    ]
