# Generated by Django 6.0.7 on 2026-07-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_staffprofile_stf_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='stf_license_expiration_date',
            field=models.DateField(blank=True, db_column='STF_LICENSE_EXPIRATION_DATE', null=True),
        ),
    ]
